name: Deploy AVD Baseline Networking to ARPA-H Tenant

on:
  # for running manually  
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose environment to deploy
        options: 
        - Test
        - Prod
      # hostpool_type:
      #   type: choice
      #   description: Choose hostpool type
      #   options: 
      #   - Pooled
      #   - Personal
      #   default: 'Personal'
      # deployment_stack_name: 
      #   type: string
      #   description: Name of deployment stack to delete
      #   default: 'Test-DevHostPool-Stack'
      update_existing_stack: 
        type: boolean
        description: Update existing stack if it exists
        default: false
  
  # for running as part of a workflow_call
#   workflow_call:
#     inputs:
#       environment:
#         required: true
#         type: string
#       deployment_stack_name:
#         required: true
#         type: string
#       update_existing_stack: 
#         type: boolean
#         description: Update existing stack if it exists
#         default: false

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    # - name: Deploy AVD Networking
    #   uses: azure/arm-deploy@v2
    #   with:
    #     scope: subscription
    #     subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
    #     region: centralus
    #     template: ./workload/bicep/deploy-baseline-arpah.bicep
    #     parameters: ./workload/bicep/parameters/deploy-baseline-parameters-arpah.json avdWorkloadSubsId=${{ secrets.SUBSCRIPTION_ID }} existingHubVnetResourceId=${{ secrets.AVD_HUB_RESOURCE_ID }} avdVnetworkAddressPrefixes=${{ secrets.AVD_VNET_ADDRESS_PREFIX }} vNetworkAvdSubnetAddressPrefix=${{ secrets.AVD_SUBNET_ADDRESS_PREFIX }} vNetworkPrivateEndpointSubnetAddressPrefix=${{ secrets.AVD_PEP_SUBNET_ADDRESS_PREFIX }}
    #     failOnStdErr: false

    - name: Deploy deployment stack to the ${{ inputs.environment }} environment
      uses: azure/powershell@v2
      with:
        inlineScript: ./.github/workflows/scripts/DeploymentStack-Baseline-Networking.ps1 -DeploymentStackName ${{ inputs.deployment_stack_name }} -Location 'centralus' `
          -TemplateFile './workload/bicep/deploy-baseline-networking-arpah.bicep' -ParametersFile './workload/bicep/parameters/deploy-baseline-parameters-networking-arpah.json' `
          -deploymentEnvironment ${{ inputs.environment }} -avdWorkloadSubsId ${{ secrets.SUBSCRIPTION_ID }} -existingHubVnetResourceId=${{ secrets.AVD_HUB_RESOURCE_ID }} `
          -avdVnetworkAddressPrefixes=${{ secrets.VNET_ADDRESS_PREFIX }} -vNetworkAvdSubnetAddressPrefix=${{ secrets.SUBNET_ADDRESS_PREFIX }} `
          -vNetworkPrivateEndpointSubnetAddressPrefix=${{ secrets.PE_SUBNET_ADDRESS_PREFIX }}
        azPSVersion: "latest"
        errorActionPreference: stop
