name: Deploy AVD to the ARPA-H Tenant
on:
    workflow_dispatch:
      inputs:
        environment:
          type: choice
          description: Choose environment to deploy
          options: 
          - personal

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    #runs-on: windows-latest
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - name: OIDC Login to Azure Public Cloud
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Deploy AVD Personal Host Pool
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          region: centralus
          template: ./workload/bicep/deploy-baseline-personal-host-pool-arpah.bicep
          parameters: ./workload/bicep/parameters/deploy-baseline-parameters-personal-host-pool-arpah.json avdWorkloadSubsId=${{ secrets.SUBSCRIPTION_ID }} avdVmLocalUserName=${{ secrets.AVD_VM_LOCALUSER_NAME }} avdVmLocalUserPassword=${{ secrets.AVD_VM_LOCALUSER_PASSWORD }} avdEnterpriseAppObjectId=${{ secrets.AZURE_AVD_OBJECT_ID }} existingHubVnetResourceId=${{ secrets.AVD_HUB_RESOURCE_ID }} avdVnetworkAddressPrefixes=${{ secrets.AVD_VNET_ADDRESS_PREFIX }} vNetworkAvdSubnetAddressPrefix=${{ secrets.AVD_SUBNET_ADDRESS_PREFIX }} vNetworkPrivateEndpointSubnetAddressPrefix=${{ secrets.AVD_PEP_SUBNET_ADDRESS_PREFIX }} existingVnetAvdSubnetResourceId=${{ secrets.AVD_SUBNET_RESOURCE_ID }} existingVnetPrivateEndpointSubnetResourceId=${{ secrets.AVD_PE_SUBNET_RESOURCE_ID }} alaExistingWorkspaceResourceId=${{ secrets.AVD_LAWS_RESOURCE_ID }}
          failOnStdErr: false

      # - name: Update AVD Application Group Display Name in the ${{ github.event.inputs.environment }} environment
      #   uses: azure/powershell@v2
      #   env:
      #     ResourceGroupName: 'avd-nih-arpah-${{ github.event.inputs.environment }}-use2-service-objects'
      #     ApplicationGroupName: 'vdag-desktop-app1-${{ github.event.inputs.environment }}-use2-001'
      #     Name: 'SessionDesktop'
      #     FriendlyName: 'ARPA-H Windows Desktop'
      #   with:
      #     inlineScript: ./.github/workflows/scripts/update_app_display_name.ps1 -ResourceGroupName ${{ env.ResourceGroupName }} -ApplicationGroupName  ${{ env.ApplicationGroupName }} -Name  ${{ env.Name }} -FriendlyName  '${{ env.FriendlyName }}'
      #     azPSVersion: "latest"
      #     errorActionPreference: continue