name: Deploy AVD Baseline to ARPA-H Tenant

on:
  # for running manually  
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose environment to deploy
        options: 
        - Test
        - Prod
      # hostpool_type:
      #   type: choice
      #   description: Choose hostpool type
      #   options: 
      #   - Pooled
      #   - Personal
      #   default: 'Personal'
      # deployment_stack_name: 
      #   type: string
      #   description: Name of deployment stack to delete
      #   default: 'Test-DevHostPool-Stack'
      # update_existing_stack: 
      #   type: boolean
      #   description: Update existing stack if it exists
      #   default: false
  
  # for running as part of a workflow_call
#   workflow_call:
#     inputs:
#       environment:
#         required: true
#         type: string
#       deployment_stack_name:
#         required: true
#         type: string
#       update_existing_stack: 
#         type: boolean
#         description: Update existing stack if it exists
#         default: false

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    env:
      KV_PREFIX: ${{ inputs.environment == 'Prod' && 'kv-se2' || 'kv-sec' }}
    
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Deploy deployment stack to the ${{ inputs.environment }} environment
      uses: azure/powershell@v2
      with:
        inlineScript: ./.github/workflows/scripts/DeploymentStack-Baseline.ps1 -DeploymentStackName ${{ inputs.deployment_stack_name }} -Location 'eastus2' -TemplateFile './workload/bicep/deploy-baseline-developer-hostpool-arpah.bicep' -ParametersFile './workload/bicep/parameters/deploy-baseline-developer-hostpool-arpah.parameters.json' `
          -deploymentEnvironment ${{ inputs.environment }} -avdWorkloadSubsId ${{ secrets.AZURE_SUB_ID }} -avdEnterpriseAppObjectId ${{ secrets.AZURE_AVD_OBJECTID }} ` 
          -existingVnetPrivateEndpointSubnetResourceId ${{ secrets.AVD_SUBNET_ID }} -securityPrincipalId "${{ secrets.DEVELOPER_SECURITY_PRINCIPAL_ID }}" -update_existing_stack ${{ inputs.update_existing_stack }} `
          -avdHostPoolType '${{ inputs.hostpool_type }}' -avdWrklKvPrefixCustomName ${{ env.KV_PREFIX }}
        azPSVersion: "latest"
        errorActionPreference: stop
